name: flutter_reactive_widget
description: Simple reactive state management for Flutter.
version: 0.0.1
homepage: https://github.com/lukehutch/flutter_reactive_widget

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter
  shared_preferences: 2.0.17

# dev_dependencies:
#   pedantic: ^1.10.0
#   test: ^1.16.0
